version: "3.8"

services:
  app:
    image: mcr.microsoft.com/devcontainers/javascript-node:20
    volumes:
      - ../..:/workspaces:cached
    working_dir: /workspaces/AI-Learning-Platform
    command: sleep infinity
    user: node
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://ailearning:postgres@postgres:5432/funlabs_ai
      - REDIS_URL=redis://redis:6379
    ports:
      - "3000:3000" # Frontend React app
      - "5000:5000" # Backend Express server
    depends_on:
      - postgres
      - redis
    networks:
      - dev-network

  postgres:
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: funlabs_ai
      POSTGRES_USER: ailearning
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - dev-network

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    volumes:
      - redis-data:/data
    ports:
      - "6379:6379"
    networks:
      - dev-network

networks:
  dev-network:
    driver: bridge

volumes:
  postgres-data:
  redis-data:
